apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: novocart
  labels:
    app: order-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: v1
    spec:
      containers:
      - name: order-service
        image: 271376211486.dkr.ecr.eu-west-1.amazonaws.com/order-service:latest
        ports:
        - containerPort: 8083
