server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/novocart_auth}
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:admin}

jwt:
  secret: ${JWT_SECRET:dev-only-change-me}
  expiration: 86400000 # 24 hours

logging:
  level:
    com.novacart.auth: DEBUG
